name: Deploy Laravel App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP environment
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3" # Specify your Laravel PHP version
          extensions: mbstring, intl, bcmath
          coverage: none

      # Install dependencies
      - name: Install dependencies
        run: |
          cd my-laravel-app
          composer install --no-dev --no-interaction --prefer-dist
          cp .env.example .env
          php artisan key:generate
      - name: Setup SSH
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Save the private key
          echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/deploy_key.pem
          chmod 600 ~/.ssh/deploy_key.pem

          # Add server to known_hosts
          ssh-keyscan -H ${{ secrets.DEPLOY_SERVER }} >> ~/.ssh/known_hosts

          # Test SSH connection
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key.pem ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} "echo 'SSH connection successful'"

      - name: Sync repository if not already present
        run: |
          rsync -avz --delete \
            --exclude 'vendor' '.git' \
            -e "ssh -i ~/.ssh/deploy_key.pem" \
            ./ \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }}:/var/www/laravel

          ssh -i ~/.ssh/deploy_key.pem ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} "
           sudo chown -R ${{ secrets.DEPLOY_USER }}:${{ secrets.DEPLOY_USER }} /var/www/laravel

      - name: Deploy to EC2
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_PATH: /var/www/laravel

        run: |
          ssh -i ~/.ssh/deploy_key.pem $DEPLOY_USER@$DEPLOY_SERVER "
            cd $DEPLOY_PATH &&
            git pull origin main &&
            cd my-laravel-app &&
            composer install --no-dev --optimize-autoloader 
          "

        # Deploy Nginx Config
      - name: Deploy Nginx Config
        env:
          DEPLOY_PATH: /var/www/laravel
          NGINX_CONF_SRC: ./nginx/laravel.conf
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
        run: |
          # Ensure nginx sites-available exists and is writable
          ssh -i ~/.ssh/deploy_key.pem $DEPLOY_USER@$DEPLOY_SERVER "if [ ! -d /etc/nginx/sites-available ]; then sudo mkdir -p /etc/nginx/sites-available; fi"

          # Copy Nginx config
          scp -i ~/.ssh/deploy_key.pem ./nginx/laravel.conf $DEPLOY_USER@$DEPLOY_SERVER:/etc/nginx/sites-available/laravel.conf

          # Set permissions for Nginx config
          ssh -i ~/.ssh/deploy_key.pem $DEPLOY_USER@$DEPLOY_SERVER "
              sudo rm -f /etc/nginx/sites-enabled/laravel.conf &&
              sudo chown $DEPLOY_USER:$DEPLOY_USER /etc/nginx/sites-available/laravel.conf &&
              sudo chmod 664 /etc/nginx/sites-available/laravel.conf &&
              sudo ln -s /etc/nginx/sites-available/laravel.conf /etc/nginx/sites-enabled/laravel.conf &&
              sudo perl -pi -e 's/_EC2_SERVER_NAME_/$DEPLOY_SERVER/g' /etc/nginx/sites-enabled/laravel.conf &&
              sudo systemctl restart nginx && sudo chown -R www-data:www-data /var/www/laravel  
          "

        # Test Laravel App with curl
      - name: Test Laravel App with curl
        run: |
          curl http://${{ secrets.DEPLOY_SERVER }}
