name: Deploy Laravel App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP environment
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3" # Specify your Laravel PHP version
          extensions: mbstring, intl, bcmath
          coverage: none

      # Install dependencies
      - name: Install dependencies
        run: |
          cd my-laravel-app
          composer install --no-dev --no-interaction --prefer-dist
          cp .env.example .env
          php artisan key:generate
      - name: Setup SSH
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          # Create .ssh directory with correct permissions
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Write the SSH key to a file
          echo "$SSH_KEY" | base64 -d > ~/.ssh/deploy_key

          # Debug SSH key file (safely)
          echo "Checking SSH key file..."
          if [ -f ~/.ssh/deploy_key ]; then
            echo "✅ SSH key file exists"
            ls -l ~/.ssh/deploy_key
          else
            echo "❌ SSH key file is missing"
          fi
          # Set correct permissions
          chmod 600 ~/.ssh/deploy_key

          # Add host key
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

          # Test SSH connection with verbose output
          ssh -v -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo 'SSH connection successful'
          "
      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          DEPLOY_PATH: /var/www/laravel

        run: |
          ssh -i ~/.ssh/deploy_key $EC2_USER@$EC2_HOST "
            cd $DEPLOY_PATH &&
            git pull origin main &&
            composer install --no-dev --optimize-autoloader &&
            php artisan migrate --force &&
            php artisan config:cache &&
            php artisan route:cache &&
            php artisan view:cache
          "
        # Deploy Nginx configuration to EC2
      - name: Deploy Nginx Config
        env:
          DEPLOY_PATH: /var/www/laravel
          NGINX_CONF_SRC: ./nginx/laravel.conf
        run: |
          scp -i ~/.ssh/deploy_key $NGINX_CONF_SRC ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/etc/nginx/sites-available/laravel
          ssh  -v -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
          sudo ln -s /etc/nginx/sites-available/laravel /etc/nginx/sites-enabled/laravel &&
          sudo systemctl restart nginx &&
          sudo chown -R www-data:www-data /var/www/laravel &&
          sudo chmod -R 755 /var/www/laravel/storage /var/www/laravel/bootstrap/cache
          "

      # Test Laravel App with curl
      - name: Test Laravel App with curl
        run: |
          curl http://$EC2_HOST
