name: Deploy Laravel App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP environment
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3" # Specify your Laravel PHP version
          extensions: mbstring, intl, bcmath
          coverage: none

      # Install dependencies
      - name: Install dependencies
        run: |
          cd my-laravel-app
          composer install --no-dev --no-interaction --prefer-dist
          cp .env.example .env
          php artisan key:generate
      - name: Setup SSH
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Save the private key
          echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/deploy_key.pem
          chmod 600 ~/.ssh/deploy_key.pem

          # Add server to known_hosts
          ssh-keyscan -H ${{ secrets.DEPLOY_SERVER }} >> ~/.ssh/known_hosts

          # Test SSH connection
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key.pem ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} "echo 'SSH connection successful'"

      - name: Clone repository if not already present
        run: |
          ssh -i ~/.ssh/deploy_key.pem ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} "
            if [ ! -d $DEPLOY_PATH/.git ]; then
              sudo rm -rf $DEPLOY_PATH &&
              sudo git clone <repository-url> $DEPLOY_PATH
            fi
          "
      - name: Deploy to EC2
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_PATH: /var/www/laravel

        run: |
          ssh -i ~/.ssh/deploy_key.pem $DEPLOY_USER@$DEPLOY_SERVER "
            cd $DEPLOY_PATH &&
            git pull origin main &&
            composer install --no-dev --optimize-autoloader &&
            php artisan migrate --force &&
            php artisan config:cache &&
            php artisan route:cache &&
            php artisan view:cache
          "
        # Deploy Nginx configuration to EC2
      - name: Deploy Nginx Config
        env:
          DEPLOY_PATH: /var/www/laravel
          NGINX_CONF_SRC: ./nginx/laravel.conf
        run: |
          scp -i ~/.ssh/deploy_key.pem $NGINX_CONF_SRC ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }}:/etc/nginx/sites-available/laravel
          ssh  -v -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key.pem ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} "
          sudo ln -s /etc/nginx/sites-available/laravel /etc/nginx/sites-enabled/laravel &&
          sudo systemctl restart nginx &&
          sudo chown -R www-data:www-data /var/www/laravel &&
          sudo chmod -R 755 /var/www/laravel/storage /var/www/laravel/bootstrap/cache
          "

      # Test Laravel App with curl
      - name: Test Laravel App with curl
        run: |
          curl http://$DEPLOY_SERVER
